### ISSUE TITLE
Bug: combine-branch should be combine-branch-name

### ISSUE THREAD

**Issue by jenseo** [vic1707/GHA-combine-PRs#9]
My github workflow doesn't like the `combine-branch` value, it seems to expect `combine-branch-name`. After looking in your implementation, it seems to be the case there as well.

`const COMBINE_BRANCH_NAME = getInput('combine-branch-name', { required: false, trimWhitespace: true });
`

So the second example in the readme needs an update I believe, I can create a PR for it

**Comment by vic1707** [comment]
You're right, just fixed it 👍
